# Generated by Django 4.2.3 on 2023-08-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('Full_Name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('Country_code', models.CharField(max_length=100, verbose_name='Country code')),
                ('Country', models.CharField(max_length=100, verbose_name='Country')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('Gender', models.CharField(max_length=100, verbose_name='Gender')),
                ('Birthdate', models.CharField(max_length=100, verbose_name='Birthdate')),
                ('Professional', models.CharField(max_length=100, verbose_name='Professional')),
                ('Personal_experiance', models.CharField(max_length=100, verbose_name='Personal experiance')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constitution', models.FileField(upload_to='home/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=100, null=True)),
                ('Message', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Book', models.FileField(null=True, upload_to='')),
                ('Book_Name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Content', models.CharField(max_length=3000, null=True)),
                ('Image', models.ImageField(upload_to='home/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
