# Generated by Django 4.2.3 on 2023-08-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_annouce_comment1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Birthdate',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Country_code',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Personal_experiance',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Professional',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment1',
            name='Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.annouce'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='user name'),
        ),
    ]
